FROM node:22-alpine

WORKDIR /app

# Copier les fichiers nécessaires
COPY package.json ./
COPY package-lock.json ./

# Installer sans dépendances de dev
RUN npm install --omit=dev

# Copier le code
COPY src ./src

CMD ["node", "src/index.js"]
